(function attachData(global) {
  const riderCombinations = [
    {
      id: "ros-canter-lordships-graffalo",
      rider: "Ros Canter",
      horse: "Lordships Graffalo",
      country: "Great Britain",
      shortCountry: "GBR",
      baseScore: 25.8,
      formScore: 94,
      reliability: 92,
      championshipExperience: 96,
      internationalStarts: 24,
      lastResultDays: 36,
      trend: 2.2,
      stamina: 91,
      travelResilience: 88,
      climateFitness: 83,
      notes: "Elite championship record with consistently low finishing scores."
    },
    {
      id: "laura-collett-london-52",
      rider: "Laura Collett",
      horse: "London 52",
      country: "Great Britain",
      shortCountry: "GBR",
      baseScore: 27.2,
      formScore: 91,
      reliability: 89,
      championshipExperience: 94,
      internationalStarts: 29,
      lastResultDays: 52,
      trend: 1.4,
      stamina: 86,
      travelResilience: 84,
      climateFitness: 82,
      notes: "Proven under pressure and usually competitive after dressage."
    },
    {
      id: "tom-mcewen-jl-dublin",
      rider: "Tom McEwen",
      horse: "JL Dublin",
      country: "Great Britain",
      shortCountry: "GBR",
      baseScore: 29.4,
      formScore: 87,
      reliability: 84,
      championshipExperience: 91,
      internationalStarts: 21,
      lastResultDays: 44,
      trend: 1.1,
      stamina: 88,
      travelResilience: 87,
      climateFitness: 81,
      notes: "Strong all-rounder with a high championship ceiling."
    },
    {
      id: "michael-jung-chipmunk-frh",
      rider: "Michael Jung",
      horse: "Chipmunk FRH",
      country: "Germany",
      shortCountry: "GER",
      baseScore: 26.6,
      formScore: 90,
      reliability: 90,
      championshipExperience: 98,
      internationalStarts: 31,
      lastResultDays: 61,
      trend: 0.8,
      stamina: 88,
      travelResilience: 90,
      climateFitness: 86,
      notes: "Benchmark dressage quality and exceptional championship history."
    },
    {
      id: "julia-krajewski-mandy",
      rider: "Julia Krajewski",
      horse: "Nickel 21",
      country: "Germany",
      shortCountry: "GER",
      baseScore: 30.1,
      formScore: 86,
      reliability: 83,
      championshipExperience: 93,
      internationalStarts: 19,
      lastResultDays: 74,
      trend: 1.7,
      stamina: 84,
      travelResilience: 82,
      climateFitness: 80,
      notes: "Fast improver with Olympic-level rider experience."
    },
    {
      id: "sandra-auffarth-viamant-du-matz",
      rider: "Sandra Auffarth",
      horse: "Viamant du Matz",
      country: "Germany",
      shortCountry: "GER",
      baseScore: 31.6,
      formScore: 82,
      reliability: 81,
      championshipExperience: 88,
      internationalStarts: 26,
      lastResultDays: 49,
      trend: 0.6,
      stamina: 89,
      travelResilience: 83,
      climateFitness: 79,
      notes: "Reliable cross-country profile with strong team value."
    },
    {
      id: "boyd-martin-fedarman-b",
      rider: "Boyd Martin",
      horse: "Fedarman B",
      country: "United States",
      shortCountry: "USA",
      baseScore: 32.4,
      formScore: 84,
      reliability: 80,
      championshipExperience: 90,
      internationalStarts: 25,
      lastResultDays: 42,
      trend: 1.2,
      stamina: 87,
      travelResilience: 86,
      climateFitness: 84,
      notes: "High-mileage championship rider with strong travel resilience."
    },
    {
      id: "tamie-smith-mai-baum",
      rider: "Tamie Smith",
      horse: "Mai Baum",
      country: "United States",
      shortCountry: "USA",
      baseScore: 30.8,
      formScore: 85,
      reliability: 79,
      championshipExperience: 84,
      internationalStarts: 18,
      lastResultDays: 93,
      trend: -0.2,
      stamina: 82,
      travelResilience: 78,
      climateFitness: 83,
      notes: "Excellent best-case score, with confidence sensitive to recency."
    },
    {
      id: "will-coleman-off-the-record",
      rider: "Will Coleman",
      horse: "Off The Record",
      country: "United States",
      shortCountry: "USA",
      baseScore: 33.1,
      formScore: 81,
      reliability: 82,
      championshipExperience: 86,
      internationalStarts: 22,
      lastResultDays: 68,
      trend: 0.4,
      stamina: 85,
      travelResilience: 80,
      climateFitness: 82,
      notes: "Consistent jumping profile and dependable team option."
    },
    {
      id: "tim-price-falco",
      rider: "Tim Price",
      horse: "Falco",
      country: "New Zealand",
      shortCountry: "NZL",
      baseScore: 29.9,
      formScore: 88,
      reliability: 86,
      championshipExperience: 92,
      internationalStarts: 27,
      lastResultDays: 58,
      trend: 1.0,
      stamina: 90,
      travelResilience: 91,
      climateFitness: 84,
      notes: "Experienced traveller with a strong finishing-score floor."
    },
    {
      id: "jonelle-price-mcclaren",
      rider: "Jonelle Price",
      horse: "McClaren",
      country: "New Zealand",
      shortCountry: "NZL",
      baseScore: 31.2,
      formScore: 84,
      reliability: 84,
      championshipExperience: 91,
      internationalStarts: 23,
      lastResultDays: 55,
      trend: 0.9,
      stamina: 88,
      travelResilience: 90,
      climateFitness: 82,
      notes: "Aggressive championship competitor with strong time performance."
    },
    {
      id: "yasmin-ingham-banzai-du-loir",
      rider: "Yasmin Ingham",
      horse: "Banzai du Loir",
      country: "Great Britain",
      shortCountry: "GBR",
      baseScore: 28.1,
      formScore: 89,
      reliability: 85,
      championshipExperience: 90,
      internationalStarts: 20,
      lastResultDays: 47,
      trend: 1.5,
      stamina: 86,
      travelResilience: 82,
      climateFitness: 81,
      notes: "Medal-level pairing with a sharp recent-form profile."
    }
  ];

  const events = [
    {
      id: "weg-aachen-2026",
      name: "World Equestrian Games",
      venue: "Aachen, Germany",
      date: "2026-08-12",
      technicality: 9,
      terrainDemand: 86,
      travelDemand: 78,
      climateStress: 64,
      pressure: 92,
      uncertainty: 12,
      countries: ["Great Britain", "Germany", "United States", "New Zealand"],
      summary: "Championship pressure, technical cross-country questions, and deep European fields."
    },
    {
      id: "olympics-la-2028",
      name: "Olympics",
      venue: "Los Angeles, United States",
      date: "2028-07-21",
      technicality: 8,
      terrainDemand: 80,
      travelDemand: 88,
      climateStress: 82,
      pressure: 98,
      uncertainty: 22,
      countries: ["Great Britain", "Germany", "United States", "New Zealand"],
      summary: "Maximum pressure with heat, travel, selection volatility, and longer-range uncertainty."
    },
    {
      id: "pau-nations-cup-2026",
      name: "FEI Nations Cup Final",
      venue: "Pau, France",
      date: "2026-10-23",
      technicality: 7,
      terrainDemand: 76,
      travelDemand: 65,
      climateStress: 58,
      pressure: 76,
      uncertainty: 9,
      countries: ["Great Britain", "Germany", "United States", "New Zealand"],
      summary: "Useful team-form indicator with lower pressure than a championship."
    }
  ];

  global.EquiBetsData = {
    riderCombinations,
    events
  };

  if (typeof module !== "undefined") {
    module.exports = global.EquiBetsData;
  }
})(typeof window !== "undefined" ? window : globalThis);
