import type { EventingResultRecord } from './results';

export const publicResults: EventingResultRecord[] = [
  {
    sourceId: 'data_fei',
    sourceRecordId: 'fei-2026-001',
    sourcePriority: 0,
    riderFeiId: '10070001',
    horseFeiId: '107AB11',
    combinationId: '10070001:107AB11',
    riderName: 'Mia Hughes',
    horseName: 'Atlas Bay',
    eventName: 'Barbury International',
    eventDate: '2026-04-11',
    level: 'CCI3-S',
    country: 'GBR',
    venue: 'Barbury Castle',
    placing: '4',
    dressageScore: 29.6,
    showJumpingPenalties: 4,
    crossCountryJumpPenalties: 0,
    crossCountryTimePenalties: 1.2,
    totalScore: 34.8,
    status: 'completed',
    merStatus: 'MER',
    sourceUrl: 'https://data.fei.org/Result/ResultList.aspx?p=barbury-cci3',
    collectedAt: '2026-04-15T08:00:00.000Z',
    isUserEntered: false,
  },
  {
    sourceId: 'data_fei',
    sourceRecordId: 'fei-2026-002',
    sourcePriority: 0,
    riderFeiId: '10070001',
    horseFeiId: '107AB11',
    combinationId: '10070001:107AB11',
    riderName: 'Mia Hughes',
    horseName: 'Atlas Bay',
    eventName: 'Burnham Market International',
    eventDate: '2026-02-28',
    level: 'CCI3-S',
    country: 'GBR',
    venue: 'Burnham Market',
    placing: '7',
    dressageScore: 30.8,
    showJumpingPenalties: 0,
    crossCountryJumpPenalties: 0,
    crossCountryTimePenalties: 4.0,
    totalScore: 34.8,
    status: 'completed',
    merStatus: 'MER',
    sourceUrl: 'https://data.fei.org/Result/ResultList.aspx?p=burnham-cci3',
    collectedAt: '2026-03-03T08:00:00.000Z',
    isUserEntered: false,
  },
  {
    sourceId: 'data_fei',
    sourceRecordId: 'fei-2026-003',
    sourcePriority: 0,
    riderFeiId: '10070002',
    horseFeiId: '108NW22',
    combinationId: '10070002:108NW22',
    riderName: 'Theo Carter',
    horseName: 'Northwind',
    eventName: 'Ocala Spring International',
    eventDate: '2026-04-04',
    level: 'CCI2-S',
    country: 'USA',
    venue: 'Ocala',
    placing: '3',
    dressageScore: 33.2,
    showJumpingPenalties: 0,
    crossCountryJumpPenalties: 0,
    crossCountryTimePenalties: 0.8,
    totalScore: 34.0,
    status: 'completed',
    sourceUrl: 'https://data.fei.org/Result/ResultList.aspx?p=ocala-cci2',
    collectedAt: '2026-04-09T08:00:00.000Z',
    isUserEntered: false,
  },
  {
    sourceId: 'data_fei',
    sourceRecordId: 'fei-2026-004',
    sourcePriority: 0,
    riderFeiId: '10070003',
    horseFeiId: '109RG33',
    combinationId: '10070003:109RG33',
    riderName: 'Sophie Bell',
    horseName: 'Riverglass',
    eventName: 'Sydney International 3 Day Event',
    eventDate: '2026-04-18',
    level: 'CCI2-S',
    country: 'AUS',
    venue: 'Sydney International Equestrian Centre',
    placing: '1',
    dressageScore: 27.9,
    showJumpingPenalties: 0,
    crossCountryJumpPenalties: 0,
    crossCountryTimePenalties: 3.6,
    totalScore: 31.5,
    status: 'completed',
    merStatus: 'MER',
    sourceUrl: 'https://data.fei.org/Result/ResultList.aspx?p=sydney-cci2',
    collectedAt: '2026-04-22T08:00:00.000Z',
    isUserEntered: false,
  },
  {
    sourceId: 'data_fei',
    sourceRecordId: 'fei-2026-005',
    sourcePriority: 0,
    riderFeiId: '10070004',
    horseFeiId: '110TF44',
    combinationId: '10070004:110TF44',
    riderName: 'Harper Wilson',
    horseName: 'Tui Flight',
    eventName: 'Taupo International',
    eventDate: '2026-03-30',
    level: 'CCI1-Intro',
    country: 'NZL',
    venue: 'National Equestrian Centre Taupo',
    placing: 'EL',
    dressageScore: 34.4,
    showJumpingPenalties: 4,
    crossCountryJumpPenalties: 20,
    crossCountryTimePenalties: 2.0,
    totalScore: null,
    status: 'eliminated',
    sourceUrl: 'https://data.fei.org/Result/ResultList.aspx?p=taupo-cci1',
    collectedAt: '2026-04-02T08:00:00.000Z',
    isUserEntered: false,
  },
];
