import type { EventingResultRecord } from './results';

export const publicResults: EventingResultRecord[] = [
  {
    sourceId: 'data_fei',
    sourceRecordId: 'fei-2026-001',
    sourcePriority: 0,
    riderName: 'Mia Hughes',
    horseName: 'Atlas Bay',
    eventName: 'Barbury International',
    eventDate: '2026-04-11',
    level: 'CCI3-S',
    country: 'GBR',
    dressageScore: 29.6,
    showJumpingPenalties: 4,
    crossCountryJumpPenalties: 0,
    crossCountryTimePenalties: 1.2,
    collectedAt: '2026-04-15T08:00:00.000Z',
    isUserEntered: false,
  },
  {
    sourceId: 'british_eventing',
    sourceRecordId: 'be-2026-119',
    sourcePriority: 20,
    riderName: 'Mia Hughes',
    horseName: 'Atlas Bay',
    eventName: 'Aston-le-Walls',
    eventDate: '2026-03-22',
    level: 'Intermediate',
    country: 'GBR',
    dressageScore: 31.1,
    showJumpingPenalties: 0,
    crossCountryJumpPenalties: 0,
    crossCountryTimePenalties: 2.4,
    collectedAt: '2026-03-25T08:00:00.000Z',
    isUserEntered: false,
  },
  {
    sourceId: 'data_fei',
    sourceRecordId: 'fei-2026-002',
    sourcePriority: 0,
    riderName: 'Mia Hughes',
    horseName: 'Atlas Bay',
    eventName: 'Burnham Market',
    eventDate: '2026-02-28',
    level: 'CCI3-S',
    country: 'GBR',
    dressageScore: 30.8,
    showJumpingPenalties: 0,
    crossCountryJumpPenalties: 0,
    crossCountryTimePenalties: 4.0,
    collectedAt: '2026-03-03T08:00:00.000Z',
    isUserEntered: false,
  },
  {
    sourceId: 'data_fei',
    sourceRecordId: 'fei-2026-003',
    sourcePriority: 0,
    riderName: 'Theo Carter',
    horseName: 'Northwind',
    eventName: 'Ocala Spring International',
    eventDate: '2026-04-04',
    level: 'CCI2-S',
    country: 'USA',
    dressageScore: 33.2,
    showJumpingPenalties: 0,
    crossCountryJumpPenalties: 0,
    crossCountryTimePenalties: 0.8,
    collectedAt: '2026-04-09T08:00:00.000Z',
    isUserEntered: false,
  },
  {
    sourceId: 'usea',
    sourceRecordId: 'usea-2026-044',
    sourcePriority: 50,
    riderName: 'Theo Carter',
    horseName: 'Northwind',
    eventName: 'Pine Top Advanced',
    eventDate: '2026-03-09',
    level: 'Preliminary',
    country: 'USA',
    dressageScore: 32.5,
    showJumpingPenalties: 4,
    crossCountryJumpPenalties: 0,
    crossCountryTimePenalties: 0,
    collectedAt: '2026-03-12T08:00:00.000Z',
    isUserEntered: false,
  },
  {
    sourceId: 'equestrian_australia',
    sourceRecordId: 'ea-2026-017',
    sourcePriority: 30,
    riderName: 'Sophie Bell',
    horseName: 'Riverglass',
    eventName: 'Sydney Eventing Classic',
    eventDate: '2026-04-18',
    level: 'CCI2-S',
    country: 'AUS',
    dressageScore: 27.9,
    showJumpingPenalties: 0,
    crossCountryJumpPenalties: 0,
    crossCountryTimePenalties: 3.6,
    collectedAt: '2026-04-22T08:00:00.000Z',
    isUserEntered: false,
  },
  {
    sourceId: 'equestrian_sports_new_zealand',
    sourceRecordId: 'esnz-2026-021',
    sourcePriority: 40,
    riderName: 'Harper Wilson',
    horseName: 'Tui Flight',
    eventName: 'Taupo Horse Trial',
    eventDate: '2026-03-30',
    level: 'CCN1',
    country: 'NZL',
    dressageScore: 34.4,
    showJumpingPenalties: 4,
    crossCountryJumpPenalties: 0,
    crossCountryTimePenalties: 2.0,
    collectedAt: '2026-04-02T08:00:00.000Z',
    isUserEntered: false,
  },
];
